config/routes.rb
Rails.application.routes.draw do

  get 'admin' => 'admin#index'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  get "sessions/create"
  get "sessions/destroy"
  resources :users

  resources :products do
    get :who_bought, on: :member
  end

  scope '(:locale)' do
    resources :orders do
      member do
        get :payment_by_ym
        get :payment_by_card
        get :payment_by_stripe
      end
    end
    resources :line_items
    resources :charges, only: [:create]
    resources :carts
    root 'store#index', as: 'store', via: :all
  end

  # get 'admin' => 'admin#index'
  # controller :sessions do
  #   get 'login' => :new
  #   post 'login' => :create
  #   delete 'logout' => :destroy
  # end

  # scope '(:locale)' do
  #   resources :orders
  #   resources :line_items
  #   resources :carts
  #   root 'store#index', as: 'store', via: :all
  # end

  # get 'admin/index'
  # get 'sessions/new'
  # get 'sessions/create'
  # get 'sessions/destroy'
  # resources :users

  # resources :products do
  #   get :who_bought, on: :member
  # end

  # root to: 'store#index', as: 'store'
  # resources :orders
  # resources :line_items
  # resources :carts
  # get 'store/index'
end

app/models/order.rb
class Order < ActiveRecord::Base
  enum pay_type: {"By Yandex Money" => 1, "By Credit card" => 2, "By Stripe" => 3}
  validates :name, :address, :email, presence: true
  validates :pay_type, inclusion: {in: Order.pay_types.keys}
  has_many :line_items, dependent: :destroy
  validates_format_of :email, with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i,
   message: 'Wrong email format'

  def add_line_items_from_cart(cart)
    cart.line_items.each do |item|
      item.cart_id = nil
      line_items << item
    end
  end

  def total_price
    line_items.to_a.sum { |item| item.total_price }
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  require 'yandex_money/api'

  include CurrentCart
  skip_before_action :authorize, only: [:new, :create, :payment_by_ym, :payment_by_card, :payment_by_stripe]
  before_action :set_cart, only: [:new, :create]
  before_action :set_order, only: [:show, :edit, :update, :destroy, :payment_by_ym, :payment_by_card, :payment_by_stripe]


  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    if @cart.line_items.empty?
      redirect_to store_url, notice: 'Your cart is empty'
      return
    end
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  def create
    @order = Order.new(order_params)
    @order.add_line_items_from_cart(@cart)

    respond_to do |format|
      if @order.save
        Cart.destroy(session[:cart_id])
        session[:cart_id] = nil
        # UserMailer.new_order_alerm(@order).deliver
        if order_params[:pay_type] == 1
          format.html { redirect_to payment_by_ym_order_path(@order), notice: I18n.t('.thanks') }
        end
        if order_params[:pay_type] == 2
          format.html { redirect_to payment_by_card_order_path(@order), notice: I18n.t('.thanks') }
        end
        if order_params[:pay_type] == 3
          format.html { redirect_to payment_by_stripe_order_path(@order.id), notice: I18n.t('.thanks') }
        end
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end


  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to payment_form_order_path(@order) }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def payment_by_ym
  end

  def payment_by_card
  end

  def payment_by_stripe
  end

  private
    def set_order
      @order = Order.find(params[:id])
    end

    def order_params
      par = params.require(:order).permit(:name, :address, :email, :pay_type)
      par[:pay_type] = par[:pay_type].to_i
      return par
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_cart_view.html.slim
h3 =t('charges.your order', order_id: @order.id)
= render(@order.line_items)
<h2 class="total_line">
  =t('charges.total price is', total_price: @order.total_price)

app/views/orders/_form.html.slim
= form_for @order do |f|
  - if @order.errors.any?
    #error_explanation
      h2 = raw t('errors.template.header', count: @order.errors.count, model: t('activerecord.models.order'))
      p = t('errors.template.body')
      ul
        - @order.errors.full_messages.each do |msg|
          li =raw msg

  .field
    = f.label :name
    = f.text_field :name, size: 40
  .field
    = f.label :address, t('.address_html')
    = f.text_area :address, rows: 3, cols: 59
  .field
    = f.label :email
    = f.text_field :email, size: 40
  .field
    = f.label :pay_type
    = f.select :pay_type, Order.pay_types, prompt: t('.pay_prompt_html')
  .actions = f.submit t('.submit')

app/views/orders/create.html.slim
=@d

app/views/orders/edit.html.slim
h1 Editing order

== render 'form'

= link_to 'Show', @order
'|
= link_to 'Back', orders_path

app/views/orders/index.html.slim
h1 Listing orders

table
  thead
    tr
      th Name
      th Address
      th Email
      th Pay type
      th
      th
      th

  tbody
    - @orders.each do |order|
      tr
        td = order.name
        td = order.address
        td = order.email
        td = order.pay_type
        td = link_to 'Show', order
        td = link_to 'Edit', edit_order_path(order)
        td = link_to 'Destroy', order, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Order', new_order_path

app/views/orders/new.html.slim
div class="depot_form"
  fieldset
    legend = t('.legend')
    == render 'form'
    = link_to 'Back', orders_path

app/views/orders/payment_by_card.html.slim
== render 'cart_view'
br
br

<form method="POST" action="https://money.yandex.ru/quickpay/confirm.xml">
    <input type="hidden" name="receiver" value="#{ ENV['yandex_wallet_id'] }">
    <input type="hidden" name="quickpay-form" value="small">
    <input type="hidden" name="targets" value="#{t('charges.order_transaction', order_id: @order.id)}">
    <input type="hidden" name="sum" value=#{@order.total_price} data-type="number">
    <input type="hidden" name="comment" value="#{t('charges.order_transaction', order_id: @order.id)}">
    <input type="hidden" name="successURL" value="http://localhost:3000/">
    <input type="hidden" name="paymentType" value="AC">
    <input type="submit" value="#{t('charges.place order')}">

app/views/orders/payment_by_stripe.html.slim
== render 'cart_view'
br
br
= form_tag charges_path do
  article
    = if flash[:error].present?
      <div id="error_explanation">
         p #{flash[:error]}
  =hidden_field_tag 'order_id', @order.id
  script src="https://checkout.stripe.com/checkout.js" class="stripe-button" data-key="#{ENV['stripe_publishable_key']}" data-description="#{t('charges.order_transaction', order_id: @order.id)}" data-locale="auto">

app/views/orders/payment_by_ym.html.slim
== render 'cart_view'
br
br

<form method="POST" action="https://money.yandex.ru/quickpay/confirm.xml">
    <input type="hidden" name="receiver" value="#{ENV['yandex_wallet_id'] }">
    <input type="hidden" name="quickpay-form" value="small">
    <input type="hidden" name="targets" value="#{t('charges.order_transaction', order_id: @order.id)}">
    <input type="hidden" name="sum" value=#{@order.total_price} data-type="number">
    <input type="hidden" name="comment" value="#{t('charges.order_transaction', order_id: @order.id)}">
    <input type="hidden" name="successURL" value="http://localhost:3000/">
    <input type="hidden" name="paymentType" value="PC">
    <input type="submit" value="#{t('charges.place order')}">

app/views/orders/show.html.slim
p#notice = notice

p
  strong Name:
  = @order.name
p
  strong Address:
  = @order.address
p
  strong Email:
  = @order.email
p
  strong Pay type:
  = @order.pay_type

= link_to 'Edit', edit_order_path(@order)
'|
= link_to 'Back', orders_path